name: ytab-local

channels:
  - conda-forge
  - bioconda

dependencies:
  - python>=3.10
  - pip
  - pandas
  - pyyaml
  - biopython
  - pysam
  - gffutils
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - matplotlib-venn
  - openpyxl
  - bowtie2
  - samtools
  - r-base
  - r-shiny
  - r-shinyfiles
  - r-bslib
  - r-dt
  - r-tidyverse
  - r-jsonlite
  - r-yaml
  - r-processx
  - r-plotly
  - r-slider
  - r-minpack.lm
  - r-ggrepel
