fitness_design_path <- function(project) file.path(project$project_root,"config","comparison_design.csv")
fitness_issues_path <- function(project) file.path(project$project_root,"config","comparison_design_issues.csv")
normalize_fitness_design_columns <- function(design) {
  if(!is.data.frame(design))return(list(valid=FALSE,data=data.frame(),missing=c("comparison_id","parent_sample","treated_sample"),message="Comparison design is not a data frame."))
  aliases<-list(comparison_id=c("comparison_id","comparison","id"),parent_sample=c("parent_sample","parent"),treated_sample=c("treated_sample","treated"),background=c("background"),pool=c("pool"),status=c("status"),included=c("included","include"),parent_summary=c("parent_summary","parent_summary_path"),treated_summary=c("treated_summary","treated_summary_path"),message=c("message","notes"))
  out<-design
  for(target in names(aliases)){source<-intersect(aliases[[target]],names(out));if(length(source)&&!target%in%names(out))out[[target]]<-out[[source[[1]]]]}
  required<-c("comparison_id","parent_sample","treated_sample");missing<-setdiff(required,names(out));message<-if(length(missing))paste0("Comparison design is missing required columns: ",paste(missing,collapse=", "),".")else""
  list(valid=!length(missing),data=out,missing=missing,message=message)
}
resolve_selected_fitness_comparisons <- function(design,selected_ids) {
  contract<-normalize_fitness_design_columns(design);ids<-unique(as.character(unname(unlist(selected_ids%||%character(),use.names=FALSE))));ids<-ids[!is.na(ids)&nzchar(trimws(ids))]
  if(!contract$valid)return(list(valid=FALSE,rows=contract$data[0,,drop=FALSE],selected_ids=ids,unknown_ids=ids,message=contract$message))
  known<-as.character(contract$data$comparison_id);unknown<-setdiff(ids,known);rows<-contract$data[known%in%ids,,drop=FALSE]
  list(valid=!length(unknown),rows=rows,selected_ids=as.character(rows$comparison_id),unknown_ids=unknown,message=if(length(unknown))paste0("Unknown comparison IDs: ",paste(unknown,collapse=", "),".")else"")
}
read_fitness_design <- function(project) {
  path<-fitness_design_path(project);if(!file.exists(path))return(data.frame());rows<-tryCatch(read.csv(path,stringsAsFactors=FALSE,check.names=FALSE),error=function(e)data.frame());contract<-normalize_fitness_design_columns(rows);if(!contract$valid){attr(rows,"design_error")<-contract$message;return(rows)};rows<-contract$data;if(!nrow(rows))return(rows)
  issues<-if(file.exists(fitness_issues_path(project)))tryCatch(read.csv(fitness_issues_path(project),stringsAsFactors=FALSE),error=function(e)data.frame())else data.frame();has_issue<-if(nrow(issues))rows$comparison_id%in%issues$comparison_id else rep(FALSE,nrow(rows));included<-tolower(as.character(rows$include))%in%c("true","1","yes");parent_path<-vapply(rows$parent_sample,function(sample){files<-list.files(file.path(project$project_root,"summary",sample),pattern="feature_table.*\\.(csv|tsv|txt)$",full.names=TRUE);if(length(files))files[[1]]else""},"");treated_path<-vapply(rows$treated_sample,function(sample){files<-list.files(file.path(project$project_root,"summary",sample),pattern="feature_table.*\\.(csv|tsv|txt)$",full.names=TRUE);if(length(files))files[[1]]else""},"");valid<-included&!has_issue&vapply(parent_path,nonempty_file,FALSE)&vapply(treated_path,nonempty_file,FALSE)&nzchar(rows$parent_sample)&nzchar(rows$treated_sample)&rows$parent_sample!=rows$treated_sample
  rows$parent_summary_path<-parent_path;rows$treated_summary_path<-treated_path;rows$valid<-valid;rows$status<-ifelse(valid,"Valid",ifelse(has_issue,"Design issue","Missing input"));rows$included<-included;rows
}
read_fitness_design_issues <- function(project) {path<-fitness_issues_path(project);if(!file.exists(path))return(data.frame());x<-tryCatch(read.csv(path,stringsAsFactors=FALSE),error=function(e)data.frame());if(nrow(x)){x$suggested_next_action<-ifelse(grepl("sample",x$issue,ignore.case=TRUE),"Review project samples","Refresh the comparison design")};x}
fitness_design_summary <- function(design,issues=data.frame()) list(valid=sum(design$valid%||%FALSE),included=sum(design$included%||%FALSE),incomplete=sum(!(design$valid%||%FALSE)),issues=nrow(issues))
fitness_default_selection <- function(design) {resolved<-normalize_fitness_design_columns(design);if(!resolved$valid||!all(c("valid","included")%in%names(resolved$data)))return(character());unname(as.character(resolved$data$comparison_id[resolved$data$valid&resolved$data$included]))}
fitness_default_analysis_id <- function(design) {if(!nrow(design))return("treated_vs_parent_raw_cpm");values<-unique(sub("^.*?-([^-]+)-treated.*$","\\1",as.character(design$treated_sample)));values<-values[nzchar(values)&values!=design$treated_sample];if(length(values)==1L)paste0(gsub("[^A-Za-z0-9_-]","_",values),"_vs_parent")else"treated_vs_parent_raw_cpm"}
validate_fitness_analysis_id <- function(value) {value<-trimws(value%||%"");if(!nzchar(value))return("Analysis ID is required.");if(grepl("\\.\\.|[/\\\\]",value)||!grepl("^[A-Za-z0-9_-]+$",value))return("Analysis ID may contain only letters, numbers, hyphens, and underscores.");""}
fitness_action_label <- function(mode="preview",cache_match=FALSE,force=FALSE)if(mode=="preview")"Preview fitness analysis"else if(force)"Rerun fitness analysis"else if(cache_match)"Use cached result"else"Run fitness analysis"
fitness_design_table <- function(design,project_root) {contract<-normalize_fitness_design_columns(design);if(!contract$valid||!nrow(contract$data))return(data.frame());x<-contract$data;optional<-function(name,default="")if(name%in%names(x))x[[name]]else rep(default,nrow(x));data.frame(Comparison=x$comparison_id,Parent=x$parent_sample,Treated=x$treated_sample,Background=optional("background"),Pool=optional("pool"),`Parent summary`=ifelse(vapply(optional("parent_summary"),nonempty_file,FALSE),"Available","Missing"),`Treated summary`=ifelse(vapply(optional("treated_summary"),nonempty_file,FALSE),"Available","Missing"),Status=optional("status"),Included=ifelse(as.logical(optional("included",FALSE)),"Yes","No"),check.names=FALSE)}
