landing_ui <- function(species_choices, detected_cpu, shinyfiles_available) {
  tags$main(class = "ytab-landing",
    tags$section(class = "ytab-hero",
      tags$div(class = "ytab-motif", HTML("<svg viewBox='0 0 760 180' aria-hidden='true'><path d='M20 100 C150 10,220 170,350 80 S600 20,740 95'/><g><circle cx='120' cy='58' r='5'/><circle cx='265' cy='120' r='5'/><circle cx='430' cy='48' r='5'/><circle cx='620' cy='110' r='5'/></g></svg>")),
      tags$div(class = "ytab-hero-copy", tags$span(class = "ytab-kicker", "LOCAL ANALYSIS WORKSPACE"),
        tags$h1("YTAB"), tags$h2("Yeast Transposon Analysis Browser"),
        tags$p("Process, quality-control, normalize, classify, and explore transposon-insertion sequencing experiments."))),
    uiOutput("landing_warning"),
    tags$section(class = "ytab-entry-grid",
      panel_card("Start new project from FASTQ",
        tags$p("Run mapping and hit-file creation locally from FASTQ files."),
        actionButton("show_new_project", "Start from FASTQ", class = "btn-primary ytab-button"),
        conditionalPanel("output.new_project_visible",
          textInput("project_id", "Project ID"),
          textInput("fastq_dir_path", "FASTQ directory path", placeholder = "/path/to/local/fastqs"),
          tags$div(class="ytab-actions", actionButton("use_fastq_path", "Use this path"),
            if (shinyfiles_available) shinyFiles::shinyDirButton("fastq_dir_choose", "Browse local folders", "Choose a directory containing FASTQ files") else tags$div(class="alert alert-warning", "The local directory chooser requires the R package shinyFiles. Update the ytab-local environment before continuing.")),
          helpText("Browsing large or network-mounted directories can be slow. Pasting the directory path above is usually faster."),
          readonly_value("Selected directory", "fastq_dir_text"),
          actionButton("scan_fastqs", "Scan FASTQs", class="btn-secondary"),
          selectInput("species", "Species/reference", choices = species_choices),
          sliderInput("threads", "CPU threads", min = 1L, max = max(2L, detected_cpu), value = min(2L, detected_cpu), step = 1L),
          conditionalPanel("input.threads > 4", tags$div(class="ytab-warning", "Higher thread counts may increase memory use on low-memory computers.")),
          uiOutput("fastq_message"),
          tags$div(id = "fastq_preview", class = "datatables html-widget html-widget-output shiny-report-size shiny-report-theme"),
          verbatimTextOutput("init_command"), uiOutput("initialize_button"),
          actionButton("return_from_new_project","Return to landing page"),verbatimTextOutput("command_output"))),
      panel_card("Import existing hit files",
        tags$p("Use CreateHitFile outputs that were already generated elsewhere, such as on an HPC."),
        actionButton("show_import_project", "Import hit files", class = "btn-primary ytab-button"),
        conditionalPanel("output.import_project_visible",
          textInput("import_project_id", "Project ID", value = "H2O2_screen_v1"),
          selectInput("import_species", "Species/reference", choices = species_choices),
          textInput("import_hit_dir_path", "CreateHitFile output directory",
            value = "output/projects/H2O2_screen_v1/create_hit_file",
            placeholder = "output/projects/project_id/create_hit_file"),
          textInput("import_metadata_path", "Optional sample metadata CSV", value = ""),
          sliderInput("import_threads", "CPU threads for downstream analyses", min = 1L, max = max(2L, detected_cpu),
            value = min(2L, detected_cpu), step = 1L),
          tags$div(class="ytab-actions",
            actionButton("import_existing_hit_project", "Import project", class="btn-primary"),
            actionButton("return_from_import_project","Return to landing page")),
          verbatimTextOutput("import_command_output"))),
      panel_card("Open an existing YTAB project",
        tags$p("Continue analysis or view results for an existing YTAB project."),
        selectizeInput("project_selector", "Project", choices = character(), selected = NULL,
          options = list(placeholder = "Select a project…")),
        checkboxInput("show_test_projects", "Show test projects", value = FALSE),
        tags$div(class="ytab-actions", actionButton("refresh_projects", "Refresh projects", class="btn-secondary ytab-button"),
          uiOutput("open_project_action")),
        uiOutput("selected_project_preview")),
      uiOutput("demo_project_card"),
      panel_card("Documentation", tags$p("Local guidance is available without an internet connection."),
        tags$div(class="ytab-actions", actionButton("view_setup_guide", "View setup guide", class="btn-secondary ytab-button"),
          actionButton("show_launch_command", "Show launch command", class="btn-secondary ytab-button")),
        uiOutput("documentation_guidance"))),
    tags$section(class="ytab-low-memory", low_memory_note()))
}
