#!/usr/bin/env Rscript
args<-commandArgs(trailingOnly=TRUE);stopifnot(length(args)==1L)
all<-commandArgs(trailingOnly=FALSE);self<-normalizePath(sub("^--file=","",grep("^--file=",all,value=TRUE)[[1L]]),winslash="/");root<-normalizePath(file.path(dirname(self),"../.."),winslash="/");config<-normalizePath(args[[1L]],winslash="/")
`%||%`<-function(left,right)if(is.null(left)||!length(left))right else left;source(file.path(root,"app/shiny/R/project_discovery.R"));source(file.path(root,"app/shiny/R/preprocessing_status.R"));source(file.path(root,"app/shiny/R/fitness_design_state.R"));source(file.path(root,"app/shiny/R/fitness_result_state.R"));project<-read_project_summary(config,root);design<-read_fitness_design(project);stopifnot(nrow(design)>0L,sum(design$valid)==4L,all(file.exists(design$parent_summary_path[design$valid])),all(file.exists(design$treated_summary_path[design$valid])))
python<-file.path(dirname(dirname(R.home())),"bin","python");if(!file.exists(python))python<-Sys.which("python");runner<-file.path(root,"scripts/local/ytab_run_treated_vs_parent.py");ids<-paste(design$comparison_id[design$valid],collapse=",")
run<-function(id,extra=character()){command_args<-c(runner,"--project-config",config,"--analysis-id",id,"--input-mode","raw-summary","--comparisons",ids,"--keep-going",extra);out<-system2(python,shQuote(command_args),stdout=TRUE,stderr=TRUE);list(status=attr(out,"status")%||%0L,output=paste(out,collapse="\n"),table=file.path(project$project_root,"treated_vs_parent",id,"treated_vs_parent_results.csv"))}
preview<-run("step13b8_fitness_preview","--dry-run");stopifnot(preview$status==0L,grepl("Resolved input mode: raw-summary",preview$output,fixed=TRUE))
plain<-run("step13b8_fitness_no_annotation");stopifnot(plain$status==0L,file.exists(plain$table));plain_validation<-validate_fitness_success("success",plain$table);stopifnot(plain_validation$valid)
annotation<-run("step13b8_fitness_classifier_annotation",c("--annotate-classifier","--classifier-target","recommended"));if(annotation$status==0L){stopifnot(file.exists(annotation$table),validate_fitness_success("success",annotation$table)$valid)}else stopifnot(grepl("classifier annotation|classifier prediction|classifier target",annotation$output,ignore.case=TRUE))
data<-read.csv(plain$table,stringsAsFactors=FALSE,check.names=FALSE);normalized<-normalize_fitness_result_columns(data);stopifnot(all(c("feature_id","fitness_call")%in%normalized$available));minimal<-data.frame(feature_id="x",fitness_call="none");stopifnot(validate_fitness_success("success",local({p<-tempfile(fileext=".csv");write.csv(minimal,p,row.names=FALSE);p}))$valid)
script<-paste(readLines(file.path(root,"scripts/ytab_treated_vs_parent_screen.R"),warn=FALSE),collapse="\n");stopifnot(!grepl("volcano",script,ignore.case=TRUE),!any(grepl("p.value|p_value|adjusted",names(data),ignore.case=TRUE)))
cat("PASS\n")
