#!/usr/bin/env Rscript
args <- commandArgs(trailingOnly = TRUE)
if (!length(args)) stop("Usage: ytab_smoke_fitness_ui.R <project.yaml>", call. = FALSE)
self <- normalizePath(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[[1]]), winslash = "/", mustWork = TRUE)
repo_root <- normalizePath(file.path(dirname(self), "../.."), winslash = "/", mustWork = TRUE)
`%||%` <- function(x, y) if (is.null(x) || !length(x)) y else x
library(shiny); library(bslib)
source(file.path(repo_root, "app/shiny/R/project_discovery.R")); source(file.path(repo_root, "app/shiny/R/ui_helpers.R"))
source(file.path(repo_root, "app/shiny/R/plot_customization_helpers.R")); source(file.path(repo_root, "app/shiny/R/qc_plot_utils.R"))
source(file.path(repo_root, "app/shiny/R/glabrata_annotation_lookup.R"))
source(file.path(repo_root, "app/shiny/R/fitness_result_state.R")); source(file.path(repo_root, "app/shiny/R/fitness_plot_utils.R"))
source(file.path(repo_root, "app/shiny/R/fitness_condition_control_plot.R"))
source(file.path(repo_root, "app/shiny/R/fitness_generated_plots.R"))
if (!exists("diagnostic_encode_relative_path")) diagnostic_encode_relative_path <- function(path) utils::URLencode(path, reserved = TRUE)
project <- read_project_summary(args[[1]], repo_root)
results <- discover_fitness_results(project); if (!length(results)) stop("No fitness result found", call. = FALSE)
result <- choose_latest_fitness_result(results); stopifnot(nrow(fitness_ma_data(result, "combined")) > 0L)
pairs <- fitness_ma_pair_choices(result)
if (length(pairs)) stopifnot(nrow(fitness_ma_data(result, "individual", unname(pairs[[1]]))) > 0L)
data <- fitness_ma_data(result, "combined"); stopifnot(all(c("mean_abundance", "log2fc", "call") %in% names(data)))
cc_data <- fitness_condition_control_plot_data(result, "combined", "")
stopifnot(nrow(cc_data) > 0L, all(c("feature_id", "control_abundance", "treated_abundance") %in% names(cc_data)))
ranked <- fitness_ma_rank_data(result, "combined", "", "both", 0L); stopifnot(all(c("rank_z_strength", "rank_lfc_strength", "rank_cpm_support", "rank_support_n", "support_pass", "candidate_rank_order", "support_class") %in% names(ranked)))
rank_cache <- list(both_0 = ranked)
get_rank <- function(direction, threshold) { key <- paste(direction, threshold, sep = "_"); if (is.null(rank_cache[[key]])) rank_cache[[key]] <<- fitness_ma_rank_data(result, "combined", "", direction, threshold); rank_cache[[key]] }
stopifnot(identical(as.numeric(fitness_ma_lfc_support_threshold()), 0))
stopifnot(identical(as.numeric(fitness_ma_candidate_lfc_threshold()), 1), identical(as.numeric(fitness_ma_candidate_cpm_threshold()), 1))
top_download <- fitness_ma_top_hits_table(result, "combined", "", "both", 10L, "top", "", 0L)
stopifnot(nrow(top_download) <= 10L, all(c("candidate_rank_order", "overall_candidate_rank", "selected_rank", "ranking_basis", "highlighted", "labeled", "annotation_source", "direction_specific_lfc_strength", "direction_specific_cpm_support", "direction_specific_z_support", "stored_call_or_final_call", "supporting_pool_ids") %in% names(top_download)))
if (nrow(top_download)) {
  annotated_top <- ytab_join_glabrata_display(top_download, repo_root, "feature_id")
  stopifnot(all(c("cagl_display_id", "gene_display_name", "cg_to_sc_relationship_display", "original_feature_id") %in% names(annotated_top)))
}
if (nrow(top_download)) stopifnot(all(top_download$direction_specific_lfc_strength >= 1), all(top_download$direction_specific_cpm_support >= 1))
if (nrow(top_download) > 1L) stopifnot(identical(as.integer(top_download$overall_candidate_rank), sort(as.integer(top_download$overall_candidate_rank))))
if (nrow(top_download)) stopifnot(identical(as.integer(top_download$selected_rank), seq_len(nrow(top_download))))
hm <- fitness_selected_hit_heatmap_data(result, top_download, "combined", "")
stopifnot(nrow(hm$data) > 0L, nrow(hm$matrix) == nrow(top_download), all(rownames(hm$matrix) %in% top_download$feature_id), all(c("gene", "rank", "hit_direction", "support_class", "contrast", "log2FC") %in% names(hm$data)))
stopifnot(all(ranked$depleted_support_n >= ranked$depleted_stored_call_n), all(ranked$enriched_support_n >= ranked$enriched_stored_call_n))
if (any(tolower(ranked$call) == "none")) stopifnot(any(tolower(ranked$call) == "none" & ranked$support_pass))
depleted_unfiltered <- get_rank("depleted", 0L)
depleted_hits <- fitness_ma_highlight_rows(depleted_unfiltered, "depleted", 50L, 0L)
if (length(depleted_hits) > 1L) {
  d <- depleted_unfiltered[depleted_hits, , drop = FALSE]
  stopifnot(all(d$log2fc <= -fitness_ma_candidate_lfc_threshold()), all(d$rank_cpm_support >= fitness_ma_candidate_cpm_threshold()))
  stopifnot(identical(as.integer(d$overall_candidate_rank), sort(as.integer(d$overall_candidate_rank))))
  stopifnot(identical(as.numeric(d$rank_lfc_strength), sort(as.numeric(d$rank_lfc_strength), decreasing = TRUE)))
}
if (any(depleted_unfiltered$rank_support_n <= 1L & depleted_unfiltered$support_pass, na.rm = TRUE)) stopifnot(TRUE)
if (any(tolower(depleted_unfiltered$call) == "none" & depleted_unfiltered$support_pass, na.rm = TRUE)) stopifnot(TRUE)
pool_ids <- fitness_ma_available_pools(result); stopifnot(length(pool_ids) >= 1L)
for (direction in c("depleted", "enriched")) {
  for (threshold in seq_len(length(pool_ids))) {
    rr <- get_rank(direction, threshold)
    hh <- fitness_ma_highlight_rows(rr, direction, 100L, threshold)
    if (length(hh)) {
      support_col <- if (direction == "depleted") "depleted_support_n" else "enriched_support_n"
      stopifnot(all(rr[[support_col]][hh] >= threshold), all(is.finite(rr$rank_z_strength[hh])))
      stopifnot(identical(as.integer(rr$overall_candidate_rank[hh]), sort(as.integer(rr$overall_candidate_rank[hh]))))
    }
  }
}
stopifnot(length(fitness_ma_highlight_rows(ranked, "both", 10L, 0L)) >= 0L)
known <- as.character(data$feature_id[[1]])
ann <- fitness_ma_annotation_rows(data, integer(), "custom", paste(known, "missing_feature", sep = ","))
stopifnot(length(ann$rows) == 1L, "missing_feature" %in% ann$unmatched)
png <- tempfile(fileext = ".png"); grDevices::png(png, width = 1800, height = 1300, res = 150); plot_fitness_ma(result, "combined", "", "both", 10L, "top", "", "medium", TRUE, 1.5); grDevices::dev.off(); stopifnot(file.exists(png), file.info(png)$size > 1000)
cc_png <- tempfile(fileext = ".png"); grDevices::png(cc_png, width = 1800, height = 1300, res = 150); plot_fitness_condition_control_scatter(result, "combined", "", "both", 10L, "top", "", "medium", TRUE, 1.5, 0L); grDevices::dev.off(); stopifnot(file.exists(cc_png), file.info(cc_png)$size > 1000)
hm_png <- tempfile(fileext = ".png"); grDevices::png(hm_png, width = 1800, height = 1300, res = 150); plot_fitness_selected_hit_heatmap(result, top_download, "combined", "", "medium"); grDevices::dev.off(); stopifnot(file.exists(hm_png), file.info(hm_png)$size > 1000)
ui <- paste(readLines(file.path(repo_root, "app/shiny/R/ui_fitness.R"), warn = FALSE), collapse = "\n")
app <- paste(readLines(file.path(repo_root, "app/shiny/app.R"), warn = FALSE), collapse = "\n")
stopifnot(grepl('"MA plot"="combined_ma"', app, fixed = TRUE), grepl("Condition versus control log-log scatter", app, fixed = TRUE), grepl("Top selected hits log2FC heatmap", app, fixed = TRUE), grepl("fitness_condition_control_plot", app, fixed = TRUE), grepl("fitness_selected_hit_heatmap", app, fixed = TRUE), grepl('c("combined_ma","condition_control","selected_hit_heatmap")', app, fixed = TRUE), grepl("fitness_ma_mode", app, fixed = TRUE), grepl("fitness_ma_hit_direction", app, fixed = TRUE), grepl("fitness_ma_annotation_mode", app, fixed = TRUE), grepl("download_fitness_ma_plot", app, fixed = TRUE), grepl("download_fitness_ma_data", app, fixed = TRUE), grepl("download_fitness_heatmap_data", app, fixed = TRUE), !grepl("Generated: Combined treated", ui, fixed = TRUE))
stopifnot(grepl("Search gene or feature ID", ui, fixed = TRUE), grepl("Full result fitness-call filter", ui, fixed = TRUE))
stopifnot(grepl("Showing %d selected top hit", app, fixed = TRUE), grepl("Showing %d of %d selected top hits matching search", app, fixed = TRUE))
stopifnot(grepl('keep <- intersect(c("selected_rank"', app, fixed = TRUE), grepl('names(x)[names(x) == "selected_rank"] <- "Rank"', app, fixed = TRUE))
stopifnot(grepl('"cagl_display_id"', app, fixed = TRUE), grepl('"gene_display_name"', app, fixed = TRUE), grepl('"cg_to_sc_relationship_display"', app, fixed = TRUE))
stopifnot(grepl('names(x)[names(x) == "cagl_display_id"] <- "CAGL ID"', app, fixed = TRUE), grepl('names(x)[names(x) == "gene_display_name"] <- "Gene name"', app, fixed = TRUE), grepl('names(x)[names(x) == "cg_to_sc_relationship_display"] <- "Cg-to-Sc relationship"', app, fixed = TRUE))
visible_keep_hit <- regexpr('keep <- intersect\\(c\\("selected_rank", "cagl_display_id", "gene_display_name", "cg_to_sc_relationship_display", "hit_direction", "pair", "log2fc", "mean_abundance", "rank_z_strength", "supporting_pool_ids"\\)', app)
stopifnot(visible_keep_hit[[1]] > 0L)
stopifnot(grepl("fitness_full_gene_search", app, fixed = TRUE), grepl("fitness_full_gene_search", ui, fixed = TRUE))
stopifnot(regexpr("Selected top hits", ui, fixed = TRUE)[[1]] < regexpr("Full result fitness-call filter", ui, fixed = TRUE)[[1]])
visible_generated <- fitness_generated_plot_inventory(project)
stopifnot(!any(visible_generated$filename %in% c("MA_y_298_labeled_top_hits.png", "MA_y_299_labeled_top_hits.png", "top_features_log2FC_heatmap.png")))
plot_utils_text <- paste(readLines(file.path(repo_root, "app/shiny/R/fitness_plot_utils.R"), warn = FALSE), collapse = "\n")
condition_text <- paste(readLines(file.path(repo_root, "app/shiny/R/fitness_condition_control_plot.R"), warn = FALSE), collapse = "\n")
stopifnot(grepl("Depleted/enriched colors reflect stored calls from local-abundance z-scores.", plot_utils_text, fixed = TRUE), !grepl("P-value", plot_utils_text, fixed = TRUE), grepl("selected_hit_colors", plot_utils_text, fixed = TRUE), grepl("Depleted selected hit", plot_utils_text, fixed = TRUE), grepl("Enriched selected hit", plot_utils_text, fixed = TRUE), grepl("M: mean abundance, log10(CPM + 1)", plot_utils_text, fixed = TRUE), grepl("A: fitness effect, log2FC treated/control", plot_utils_text, fixed = TRUE), grepl("More than 10 labels may overlap; reduce Number of hits for cleaner labels.", plot_utils_text, fixed = TRUE), grepl("fitness_ma_label_table", plot_utils_text, fixed = TRUE), grepl("segments(label_table$data", plot_utils_text, fixed = TRUE), grepl("0.11 * xr", plot_utils_text, fixed = TRUE), !grepl("MA_y_298_labeled_top_hits", plot_utils_text, fixed = TRUE), !grepl("MA_y_299_labeled_top_hits", plot_utils_text, fixed = TRUE), !grepl('legend(\"topleft\", legend = \"Top hits highlighted\"', plot_utils_text, fixed = TRUE))
stopifnot(grepl("parent_cpm", condition_text, fixed = TRUE), grepl("treated_cpm", condition_text, fixed = TRUE), grepl("Control abundance, log10(CPM + 1)", condition_text, fixed = TRUE), grepl("Treated abundance, log10(CPM + 1)", condition_text, fixed = TRUE), grepl("abline(0, 1", condition_text, fixed = TRUE), grepl("fitness_ma_rank_data", condition_text, fixed = TRUE), grepl("fitness_ma_highlight_rows", condition_text, fixed = TRUE), grepl("Below diagonal = depleted in treatment; above diagonal = enriched in treatment.", condition_text, fixed = TRUE))
stopifnot(grepl("fitness_selected_hit_heatmap_data", plot_utils_text, fixed = TRUE), grepl("Top selected hits log2FC heatmap", plot_utils_text, fixed = TRUE), grepl("Rows = currently selected hits", plot_utils_text, fixed = TRUE), grepl("log2FC treated/control", plot_utils_text, fixed = TRUE))
generated_text <- paste(readLines(file.path(repo_root, "app/shiny/R/fitness_generated_plots.R"), warn = FALSE), collapse = "\n")
stopifnot(grepl("top_features_log2FC_heatmap.png", generated_text, fixed = TRUE))
none_labels <- fitness_ma_label_table(ranked, fitness_ma_highlight_rows(ranked, "depleted", 10L, 0L), "none", "", "combined", "")
stopifnot(!nrow(none_labels$data))
if (length(pairs)) {
  stopifnot(nrow(fitness_condition_control_plot_data(result, "individual", unname(pairs[[1]]))) > 0L)
  pair_data <- fitness_ma_rank_data(result, "individual", unname(pairs[[1]]), "depleted", 0L); pair_hi <- fitness_ma_highlight_rows(pair_data, "depleted", 10L, 0L)
  stopifnot(all(c("rank_z_strength", "rank_lfc_strength", "rank_cpm_support") %in% names(pair_data)), all(pair_data$selected_min_support_pools == 0L))
  pair_none <- fitness_ma_label_table(pair_data, pair_hi, "none", "", "individual", unname(pairs[[1]]))
  stopifnot(!nrow(pair_none$data), all(fitness_ma_label_table(pair_data, pair_hi, "top", "", "individual", unname(pairs[[1]]))$data$comparison_view == "individual_pair"))
}
none_ranked <- fitness_ma_rank_data(result, "combined", "", "none", 0L); none_hits <- fitness_ma_highlight_rows(none_ranked, "none", 10L, 0L); stopifnot(!length(none_hits), !any(none_ranked$support_pass))
custom_only <- fitness_ma_annotation_rows(ranked, fitness_ma_highlight_rows(ranked, "depleted", 10L, 0L), "custom", "missing_feature")
stopifnot(!length(custom_only$rows), "missing_feature" %in% custom_only$unmatched)
top_only <- fitness_ma_annotation_rows(ranked, fitness_ma_highlight_rows(ranked, "depleted", 10L, 0L), "top", "")
stopifnot(all(top_only$rows %in% fitness_ma_highlight_rows(ranked, "depleted", 10L, 0L)))
app_ui <- paste(readLines(file.path(repo_root, "app/shiny/app.R"), warn = FALSE), collapse = "\n")
stopifnot(grepl("fitness_ma_min_support", app_ui, fixed = TRUE), grepl("Concordance filter", app_ui, fixed = TRUE), grepl("All support classes", app_ui, fixed = TRUE), !grepl("top100_depleted_in_treated", paste(readLines(file.path(repo_root, "app/shiny/R/fitness_plot_utils.R"), warn = FALSE), collapse = "\n"), fixed = TRUE))
cat("PASS\n")
